name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker images for Frontend and Backend
      run: |
        docker build -f ./frontend/Dockerfile --build-arg NEXT_PUBLIC_BACKEND_URL=${{ secrets.BACKEND_API_ENDPOINT }} -t ${{ secrets.ACR_LOGIN_SERVER }}/aura-ai-frontend:latest ./frontend
        docker build -f ./backend/Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/aura-ai-backend:latest ./backend

    - name: Log in to ACR
      run: |
        az acr login --name ${{ secrets.ACR_REPOSITORY_NAME }}

    - name: Push Docker images to ACR
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/aura-ai-frontend:latest
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/aura-ai-backend:latest

    - name: Deploy frontend to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_APP_SERVICE_FRONTEND }} 
        images: |
          ${{ secrets.ACR_LOGIN_SERVER }}/aura-ai-frontend:latest

    - name: Deploy backend to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_APP_SERVICE_BACKEND }}
        images: |
          ${{ secrets.ACR_LOGIN_SERVER }}/aura-ai-backend:latest